package com.team1.paymentsystem.states;

public enum Operation {
    LIST, CREATE, REPAIR, MODIFY, BLOCK,
    BLOCK_CREDIT, BLOCK_DEBIT, UNBLOCK, UNBLOCK_CREDIT, UNBLOCK_DEBIT,
    CLOSE, REMOVE,
    APPROVE, REJECT, VERIFY, AUTHORIZE, CANCEL,
    UNBLOCK_FRAUD, CREATE_MOBILE;
}
